name = "MemArena"
uuid = "3ddf64ce-8ba0-4bf8-b73f-569113a798d7"
authors = ["Jack Coughlin <jack@johnbcoughlin.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
